package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

// Unrestricted addresses (Constitution §126-130).
//
//	§126  "$GNOT will not be transferrable initially except for whitelisted
//	       addresses. Whitelisted addresses include "Ecosystem" and "Investors"
//	       funds and any additional addresses needed for the operation of the
//	       chain, and funding needs or payment of investors. Whitelisted funds
//	       remain subject to the vesting schedule below."
//
// Two things that clause settles, and that are easy to get backwards:
//
//   - Transfers are locked at genesis. That is not a policy option — §126 says
//     "will not be transferrable initially". A chain that launches open has no
//     use for this file, but it also has no §126.
//   - Whitelisting is NOT unlocking. The last sentence is explicit: whitelisted
//     funds still vest. So the investors-vesting tranche belongs on this list
//     and keeps its §132 schedule. The two mechanisms are independent.
//
// This file is GENERATED so the list cannot drift from the sheet it describes.
// The public-sale rows are read from publicsale.txt rather than restated, so a
// participant who binds an address after the last build cannot be silently
// omitted: the row appears in both files or in neither.
// addrRE is the canonical bech32 gno address shape, as used by the balance
// sheet validators in allocate/.
var addrRE = regexp.MustCompile(`^g1[0-9a-z]{38}$`)

const (
	// The three funds §127 names. Kept in step with allocate/ by
	// TestUnrestrictedNamedFundsMatchAllocate, which parses the constants out of
	// allocate/process_consolidated.go rather than trusting this copy.
	unrestrictedEcosystem         = "g1ugke9x9ylrlex0lxcgw7eu0mdftvcrgglru0l0"
	unrestrictedInvestorsUnlocked = "g1j3et7juxr3npgdll3lml3mpv0y6m49rztjnf76"
	unrestrictedInvestorsVesting  = "g1x7tm26g9wj84cmg3cs74uwf3g9lqj4mjp6gax3"
)

const unrestrictedHeader = `# Unrestricted addresses — Constitution §126-130.
#
# GENERATED by mkgenesis; do not edit. Rebuild with:
#
#     make -C mkgenesis unrestricted.txt
#
# At genesis $GNOT is globally non-transferable. §126 requires an exemption list,
# and this is it. Consumers strip everything from '#' to end of line and ignore
# blank lines — the same convention as non-airdrop.txt.
#
# WHITELISTING IS NOT UNLOCKING. §129: "Whitelisted funds remain subject to the
# vesting schedule below." The investors-vesting tranche is on this list AND
# keeps its §132 schedule; the two mechanisms are independent.
#
# NOT on this list, deliberately — each needs a ruling, not a default:
#   NT,LLC          §124 is "for use at NT,LLC discretion"; §127 does not name it
#   Core Treasury   §127 names only "Ecosystem" by name
#   Validator Svcs  ditto, though §128's "operation of the chain" may cover it
#   nt2 / AiB       has no Constitution bucket at all, so no whitelist authority
#
# There is no faucet on mainnet, so there is no faucet entry.
`

func runUnrestricted(args []string) error {
	fs := flag.NewFlagSet("unrestricted", flag.ExitOnError)
	sale := fs.String("publicsale", "publicsale.txt", "public-sale sheet to read the participants from")
	out := fs.String("out", "unrestricted.txt", "generated address list")
	if err := fs.Parse(args); err != nil {
		return err
	}

	saleAddrs, err := readAddresses(*sale)
	if err != nil {
		return err
	}
	if len(saleAddrs) == 0 {
		return fmt.Errorf("%s produced no addresses — refusing to write an exemption list that silently omits the sale", *sale)
	}

	var b strings.Builder
	b.WriteString(unrestrictedHeader)
	b.WriteString("\n# Ecosystem Treasury — §127 names it explicitly.\n")
	b.WriteString(unrestrictedEcosystem + "\n")
	b.WriteString("\n# Investors funds — §127 names them explicitly.\n")
	b.WriteString(unrestrictedInvestorsUnlocked + " # unlocked tranche, §136\n")
	b.WriteString(unrestrictedInvestorsVesting + " # vesting tranche, §132 — still vests, see §129\n")
	fmt.Fprintf(&b, "\n# Public token sale — §128 \"payment of investors\". %d rows, from %s.\n",
		len(saleAddrs), *sale)
	for _, a := range saleAddrs {
		b.WriteString(a + "\n")
	}

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("%s: %d addresses (3 named funds + %d public sale)\n",
		*out, 3+len(saleAddrs), len(saleAddrs))
	return nil
}

// readAddresses returns the sorted, de-duplicated addresses of a sheet.
// Everything from the first '#' is a comment, matching non-airdrop.txt.
//
// Accepts both shapes: "<addr>=<coins>" (a balance sheet) and a bare "<addr>"
// (the exemption list this file generates), so the same reader round-trips its
// own output.
func readAddresses(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	seen := map[string]bool{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(stripComment(sc.Text()))
		if line == "" {
			continue
		}
		addr, _, _ := strings.Cut(line, "=")
		addr = strings.TrimSpace(addr)
		if !addrRE.MatchString(addr) {
			return nil, fmt.Errorf("%s: malformed row %q", path, line)
		}
		seen[addr] = true
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}

	addrs := make([]string, 0, len(seen))
	for a := range seen {
		addrs = append(addrs, a)
	}
	sort.Strings(addrs)
	return addrs, nil
}
