package main

import (
	"bufio"
	"compress/gzip"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// syntheticHRP is the prefix of a row that was assigned rather than derived
// from a snapshot: the buckets, the founders and the validator gas float. Every
// other row carries the chain prefix of the snapshot the entitlement came from.
const syntheticHRP = "g1"

// runReadme regenerates README.md from the committed genbalance.txt.gz.
//
// Every figure the README states is read back out of the artifact rather than
// typed, because the hand-written version drifted: it claimed 3,262,457 rows
// and an example row paying an address that no longer exists.
func runReadme(args []string) error {
	fs := flag.NewFlagSet("readme", flag.ExitOnError)
	genbalance := fs.String("genbalance", outputFile, "allocation output to report on")
	out := fs.String("out", "README.md", "generated report")
	if err := fs.Parse(args); err != nil {
		return err
	}

	report, err := readGenbalance(*genbalance)
	if err != nil {
		return err
	}

	if err := os.WriteFile(*out, []byte(report.render(filepath.Base(*genbalance))), 0o644); err != nil {
		return err
	}

	fmt.Printf("%s: %d rows, %d ugnot\n", *out, report.rows, report.total)
	return nil
}

// genbalanceReport is everything the generated README states about the file.
type genbalanceReport struct {
	rows      int
	total     int64
	sources   map[string]int    // hrp -> row count
	samples   map[string]string // hrp -> first row seen with that prefix
	synthetic []string          // every g1… row, in file order
}

func readGenbalance(path string) (*genbalanceReport, error) {
	r := &genbalanceReport{
		sources: make(map[string]int),
		samples: make(map[string]string),
	}

	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	zr, err := gzip.NewReader(f)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	defer zr.Close()

	sc := bufio.NewScanner(zr)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	for n := 1; sc.Scan(); n++ {
		line := sc.Text()
		if strings.TrimSpace(line) == "" {
			continue
		}

		source, amount, err := parseGenbalanceRow(line)
		if err != nil {
			return nil, fmt.Errorf("%s:%d: %w", path, n, err)
		}

		r.rows++
		sum := r.total + amount
		if sum < r.total {
			return nil, fmt.Errorf("%s:%d: total overflows int64", path, n)
		}
		r.total = sum

		hrp := sourceHRP(source)
		r.sources[hrp]++
		if _, seen := r.samples[hrp]; !seen {
			r.samples[hrp] = line
		}
		if hrp == syntheticHRP {
			r.synthetic = append(r.synthetic, line)
		}
	}

	return r, sc.Err()
}

// parseGenbalanceRow splits `source:gnoaddr=<amount>ugnot`. The source column is
// what makes the file auditable, so a row missing it is an error rather than
// something to skip.
func parseGenbalanceRow(line string) (source string, amount int64, err error) {
	colon := strings.IndexByte(line, ':')
	if colon < 0 {
		return "", 0, fmt.Errorf("no source column in %q", line)
	}
	eq := strings.IndexByte(line[colon:], '=')
	if eq < 0 {
		return "", 0, fmt.Errorf("no amount in %q", line)
	}

	raw := strings.TrimSuffix(line[colon+eq+1:], "ugnot")
	amount, err = strconv.ParseInt(raw, 10, 64)
	if err != nil {
		return "", 0, fmt.Errorf("amount %q in %q: %w", raw, line, err)
	}
	return line[:colon], amount, nil
}

// sourceHRP reduces a bech32 address to the prefix that identifies which
// snapshot it came from: cosmos1…, atone1… or the synthetic g1….
func sourceHRP(addr string) string {
	if i := strings.IndexByte(addr, '1'); i >= 0 {
		return addr[:i+1]
	}
	return addr
}

func (r *genbalanceReport) render(name string) string {
	var b strings.Builder

	b.WriteString("<!-- Code generated by `go run . readme`. DO NOT EDIT. -->\n\n")
	b.WriteString("# allocate/ — what the allocation engine produced\n\n")
	b.WriteString("Every figure below is read back out of the committed `" + name + "`.\n")
	b.WriteString("The hand-written explanation of this stage lives in [`ABOUT.md`](./ABOUT.md);\n")
	b.WriteString("regenerate this file with `cd allocate && go run . readme`.\n\n")

	b.WriteString("## rows\n```\n")
	fmt.Fprintf(&b, "%d %s\n", r.rows, name)
	b.WriteString("```\n\n")

	b.WriteString("## sum\n```\n")
	fmt.Fprintf(&b, "%dugnot\n", r.total)
	fmt.Fprintf(&b, "%dgnot\n", r.total/1000000)
	b.WriteString("```\n\n")

	b.WriteString("## rows by source\n\n")
	b.WriteString("The first column of every row is the source the entitlement came from, so this is\n")
	b.WriteString("the breakdown of the output by origin chain.\n\n")
	b.WriteString("| Source | Rows |\n|---|---:|\n")
	for _, hrp := range r.sortedHRPs() {
		fmt.Fprintf(&b, "| `%s…` | %d |\n", hrp, r.sources[hrp])
	}
	fmt.Fprintf(&b, "| **total** | **%d** |\n\n", r.rows)

	b.WriteString("## sample rows\n\n")
	b.WriteString("One real row per source, so the format below is never an invented example.\n\n")
	b.WriteString("```\n")
	for _, hrp := range r.sortedHRPs() {
		b.WriteString(r.samples[hrp])
		b.WriteByte('\n')
	}
	b.WriteString("```\n\n")

	fmt.Fprintf(&b, "## the %d synthetic rows\n\n", len(r.synthetic))
	b.WriteString("Rows whose source is a `g1…` address are assigned by `process_consolidated.go`\n")
	b.WriteString("rather than derived from a snapshot: the purpose-bound buckets, the founders\n")
	b.WriteString("and the founding validator set's gas float.\n")
	b.WriteString("They are listed in full because they are the rows a reviewer must check by eye.\n\n")
	b.WriteString("```\n")
	for _, line := range r.synthetic {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString("```\n")

	return b.String()
}

func (r *genbalanceReport) sortedHRPs() []string {
	hrps := make([]string, 0, len(r.sources))
	for hrp := range r.sources {
		hrps = append(hrps, hrp)
	}
	sort.Strings(hrps)
	return hrps
}
